/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="text-yellow-950 text-7xl font-bold leading-[96px] whitespace-nowrap max-md:max-w-full max-md:text-4xl max-md:leading-[59px]">
      <span className="text-gray-800">From Kitchen</span>
      <span className="text-white"> </span>
      <span className="text-yellow-950">to your Table</span>
    </div>
  );
}
